export const GET_INGREDIENTS_REQUEST: "INGREDIENTS/GET_REQUEST" =
  "INGREDIENTS/GET_REQUEST";
export const GET_INGREDIENTS_SUCCESS: "INGREDIENTS/GET_SUCCESS" =
  "INGREDIENTS/GET_SUCCESS";
export const GET_INGREDIENTS_FAILED: "INGREDIENTS/GET_FAILED" =
  "INGREDIENTS/GET_FAILED";
export const CHANGE_TAB: "CHANGE_TAB" = "CHANGE_TAB";
