export const GET_ORDER_REQUEST: "ORDER/GET_REQUEST" = "ORDER/GET_REQUEST";
export const GET_ORDER_SUCCESS: "ORDER/GET_SUCCESS" = "ORDER/GET_SUCCESS";
export const GET_ORDER_FAILED: "ORDER/GET_FAILED" = "ORDER/GET_FAILED";
export const NUMBER_RESET: "NUMBER_RESET" = "NUMBER_RESET";
