export const GET_USER_REQUEST: "USER/GET_REQUEST" = "USER/GET_REQUEST";
export const GET_USER_SUCCESS: "USER/GET_SUCCESS" = "USER/GET_SUCCESS";
export const GET_USER_FAILED: "USER/GET_FAILED" = "USER/GET_FAILED";

export const UPDATE_USER_REQUEST: "USER/UPDATE_REQUEST" = "USER/UPDATE_REQUEST";
export const UPDATE_USER_SUCCESS: "USER/UPDATE_SUCCESS" = "USER/UPDATE_SUCCESS";
export const UPDATE_USER_FAILED: "USER/UPDATE_FAILED" = "USER/UPDATE_FAILED";

export const CLEAR_USER_DATA: "CLEAR_USER_DATA" = "CLEAR_USER_DATA";
export const AUTHENTICATE_USER: "AUTHENTICATE_USER" = "AUTHENTICATE_USER";
export const UNAUTHENTICATE_USER: "UNAUTHENTICATE_USER" = "UNAUTHENTICATE_USER";

export const GET_LOGIN_REQUEST: "LOGIN/GET_REQUEST" = "LOGIN/GET_REQUEST";
export const GET_LOGIN_SUCCESS: "LOGIN/GET_SUCCESS" = "LOGIN/GET_SUCCESS";
export const GET_LOGIN_FAILED: "LOGIN/GET_FAILED" = "LOGIN/GET_FAILED";

export const GET_LOGOUT_REQUEST: "LOGOUT/GET_REQUEST" = "LOGOUT/GET_REQUEST";
export const GET_LOGOUT_SUCCESS: "LOGOUT/GET_SUCCESS" = "LOGOUT/GET_SUCCESS";
export const GET_LOGOUT_FAILED: "LOGOUT/GET_FAILED" = "LOGOUT/GET_FAILED";

export const GET_REGISTRATION_REQUEST: "REGISTRATION/GET_REQUEST" =
  "REGISTRATION/GET_REQUEST";
export const GET_REGISTRATION_SUCCESS: "REGISTRATION/GET_SUCCESS" =
  "REGISTRATION/GET_SUCCESS";
export const GET_REGISTRATION_FAILED: "REGISTRATION/GET_FAILED" =
  "REGISTRATION/GET_FAILED";

export const GET_FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD/GET_REQUEST" =
  "FORGOT_PASSWORD/GET_REQUEST";
export const GET_FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD/GET_SUCCESS" =
  "FORGOT_PASSWORD/GET_SUCCESS";
export const GET_FORGOT_PASSWORD_FAILED: "FORGOT_PASSWORD/GET_FAILED" =
  "FORGOT_PASSWORD/GET_FAILED";
export const IS_PASSWORD_REQUESTED: "IS_PASSWORD_REQUESTED" =
  "IS_PASSWORD_REQUESTED";

export const GET_RESET_PASSWORD_REQUEST: "RESET_PASSWORD/GET_REQUEST" =
  "RESET_PASSWORD/GET_REQUEST";
export const GET_RESET_PASSWORD_SUCCESS: "RESET_PASSWORD/GET_SUCCESS" =
  "RESET_PASSWORD/GET_SUCCESS";
export const GET_RESET_PASSWORD_FAILED: "RESET_PASSWORD/GET_FAILED" =
  "RESET_PASSWORD/GET_FAILED";
export const IS_PASSWORD_RESETED: "IS_PASSWORD_RESETED" = "IS_PASSWORD_RESETED";
