import {
  WS_CONNECTION_START,
  WS_CONNECTION_SUCCESS,
  WS_CONNECTION_ERROR,
  WS_CONNECTION_CLOSED,
  WS_GET_MESSAGE,
  WS_SEND_MESSAGE,
} from "../constants/ws";
import {
  WS_PROFILE_CONNECTION_START,
  WS_PROFILE_CONNECTION_SUCCESS,
  WS_PROFILE_CONNECTION_CLOSED,
  WS_PROFILE_CONNECTION_ERROR,
  WS_PROFILE_GET_MESSAGE,
  WS_PROFILE_SEND_MESSAGE,
} from "../constants/ws-auth";

export type TWebSocketActions = {
  onStart: typeof WS_CONNECTION_START | typeof WS_PROFILE_CONNECTION_START;
  onOpen: typeof WS_CONNECTION_SUCCESS | typeof WS_PROFILE_CONNECTION_SUCCESS;
  onClose: typeof WS_CONNECTION_CLOSED | typeof WS_PROFILE_CONNECTION_CLOSED;
  onError: typeof WS_CONNECTION_ERROR | typeof WS_PROFILE_CONNECTION_ERROR;
  onMessage: typeof WS_GET_MESSAGE | typeof WS_PROFILE_GET_MESSAGE;
  onSendMessage: typeof WS_SEND_MESSAGE | typeof WS_PROFILE_SEND_MESSAGE;
};
